services:
  reverse-proxy:
    image: traefik:v3
    container_name: ct-traefik
    hostname: ct-traefik
    ports:
      - 80:80
      - 443:443
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/traefik.toml:/etc/traefik/traefik.toml
      - ../config/acme.json:/acme.json
    restart: unless-stopped
    networks:
      - web
networks:
  web:
    external: true