services:
  reverse-proxy:
    image: traefik:v3
    container_name: ct-traefik
    hostname: ct-traefik
    ports:
      - 80:80
      - 443:443
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/traefik.toml:/etc/traefik/traefik.toml
      - ../config/acme.json:/acme.json
    restart: unless-stopped
    networks:
      - web
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.api.rule=Host('localhost') && (PathPrefix('/api') || PathPrefix('/dashboard'))"
       - "traefik.http.routers.api.service=api@internal"
       - "traefik.http.routers.api.entrypoints=websecure"
       - "traefik.http.middlewares.strip-www.redirectregex.regex=^https?://(www\\.)(.+)"
       - "traefik.http.middlewares.strip-www.redirectregex.replacement=https://$${2}"
       - "traefik.http.middlewares.strip-www.redirectregex.permanent=true"

networks:
  web:
    external: true